name: beauty_supplies_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"



dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  firebase_core: ^1.20.0
  flutter_bloc: ^8.1.1
  shared_preferences: ^2.0.15
  flutter_native_splash: ^2.2.8
  flutter_launcher_icons: ^0.10.0
  image_picker: ^0.8.5+3
  hexcolor: ^2.0.7
  fluttertoast: ^8.0.9
  firebase_auth: ^3.7.0
  cloud_firestore: ^3.4.6
  carousel_slider: ^4.1.1
  cached_network_image: ^3.2.1
  flutter_rating_bar: ^4.0.1
  smooth_page_indicator: ^1.0.0+2
  dropdown_search: ^5.0.3
  sqflite: ^2.2.0+2





dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^2.0.0



flutter:



  uses-material-design: true


  assets:
    - assets/images/


  fonts:
    - family: IconBroken
      fonts:
        - asset: assets/icons/icons.ttf

    - family: MyFont
      fonts:
        - asset: assets/fonts/font.ttf
          weight: 700

