// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc3niaVs6wMJwny9apegOgtLJMCxbsZv0',
    appId: '1:469974751448:web:2101e98a94413ab0c75fad',
    messagingSenderId: '469974751448',
    projectId: 'beauty-supplies-14641',
    authDomain: 'beauty-supplies-14641.firebaseapp.com',
    storageBucket: 'beauty-supplies-14641.appspot.com',
    measurementId: 'G-DDTQCGG62S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtzZPs7eYd2WkSAVzFfG1wGC-U7h2Bnl4',
    appId: '1:469974751448:android:4d4602ee5741875fc75fad',
    messagingSenderId: '469974751448',
    projectId: 'beauty-supplies-14641',
    storageBucket: 'beauty-supplies-14641.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV2UWrc7cnyiu9OzXCNpVv2UltbdfYVi8',
    appId: '1:469974751448:ios:a5e9c1762e7b263ec75fad',
    messagingSenderId: '469974751448',
    projectId: 'beauty-supplies-14641',
    storageBucket: 'beauty-supplies-14641.appspot.com',
    androidClientId: '469974751448-v6kfq7u38la5obirked5k4dt8lente5t.apps.googleusercontent.com',
    iosClientId: '469974751448-5kr9knmefvirin96l2gkv1usskbavnld.apps.googleusercontent.com',
    iosBundleId: 'com.supplies.beauty.beautySuppliesProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV2UWrc7cnyiu9OzXCNpVv2UltbdfYVi8',
    appId: '1:469974751448:ios:a5e9c1762e7b263ec75fad',
    messagingSenderId: '469974751448',
    projectId: 'beauty-supplies-14641',
    storageBucket: 'beauty-supplies-14641.appspot.com',
    androidClientId: '469974751448-v6kfq7u38la5obirked5k4dt8lente5t.apps.googleusercontent.com',
    iosClientId: '469974751448-5kr9knmefvirin96l2gkv1usskbavnld.apps.googleusercontent.com',
    iosBundleId: 'com.supplies.beauty.beautySuppliesProject',
  );
}
